version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # Group all updates into one PR per week
    groups:
      all-updates:
        patterns: ["*"]
        update-types: ["patch", "minor"]

    # Ignore major updates (breaking changes)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
